### ISSUE TITLE
how is the repo organised?

### ISSUE THREAD

**Issue by dgamma3** [alexkuttig/prn-videoexample#2]
I can't see a branch for each chapter?
only 11, and 12 branches

**Comment by alexkuttig** [comment]
Hi @dgamma3,
this repo is organized with tags. You can find them here: 
![Bildschirmfoto 2023-03-24 um 14 04 01](https://user-images.githubusercontent.com/4570660/227528732-62e65f2c-afe7-4418-8640-e628f7f06eb9.png)
With these tags you can recreate this repository step by step, to learn chapter by chapter.
